### ISSUE TITLE
Round card images return 403 in some cases

### ISSUE THREAD

**Issue by konistehrad** [SchoolIdolTomodachi/SchoolIdolAPI#138]
From an experiment I was doing:

8round.jpg: 1 GET http://i.schoolido.lu/web/static/cards/8round.jpg 403 (Forbidden)
10round.jpg:1 GET http://i.schoolido.lu/web/static/cards/10round.jpg 403 (Forbidden)
9round.jpg: 1 GET http://i.schoolido.lu/web/static/cards/9round.jpg 403 (Forbidden)
7round.jpg: 1 GET http://i.schoolido.lu/web/static/cards/7round.jpg 403 (Forbidden)
11round.jpg:1 GET http://i.schoolido.lu/web/static/cards/11round.jpg 403 (Forbidden)
12round.jpg:1 GET http://i.schoolido.lu/web/static/cards/12round.jpg 403 (Forbidden)

I saw in #48 that not all cards are available, those seem to return empty strings and do not fail in the same way.

Thanks again for this exceptional tool!

**Comment by db0company** [comment]
Thanks for reporting this. It should be fixed now. Can you confirm?

**Comment by konistehrad** [comment]
Almost all succeed, tho 7 still fails:

http://i.schoolido.lu/web/static/cards/7round.jpg Failed to load resource: the server responded with a status of 403 (Forbidden)

Out of all with round images this appears to be the only one. This is after a hard refresh.

**Comment by db0company** [comment]
Fixed. Thanks!
